# Generated by Django 5.2.7 on 2025-10-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('grades', '0001_initial'),
        ('students', '0003_alter_student_date_of_birth_alter_student_gender'),
        ('subjects', '0002_remove_subject_created_at_remove_subject_credits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-graded_at', 'title']},
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='class_name',
            new_name='class_id',
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'class_id', 'title', 'graded_at')},
        ),
        migrations.AddField(
            model_name='grade',
            name='graded_at',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('exam', 'Exam'), ('midterm', 'Midterm'), ('final', 'Final')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='graded_date',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='weight',
        ),
    ]
