# Generated by Django 5.2.5 on 2025-10-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_options_rename_class_name_grade_class_id_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Manual migration to fix database schema after manual changes
            -- This migration marks the database as migrated without making changes
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
