# Generated by Django 5.2.7 on 2025-10-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
    ]
